const base_site = "https://kadschool.com/backend/kad_api/";
const urls = {
  kelasses: `${base_site}kelases`,
  teachers: `${base_site}teachers`,
  doreha: `${base_site}doreha`,
  all_courses: `${base_site}all_courses`,
  courses: `${base_site}courses`,
  sample_files: `${base_site}sample_files`,
  jalasat: `${base_site}jalasat`,
  banners: `${base_site}admin_banners`,
  user: `${base_site}user/`,
  finance_records: `${base_site}financial_records/`,
  register_user: `${base_site}register_user`,
  verify_number: `${base_site}verify_phone_number/`,
  apollo: `${base_site}apollo11_add_phone_number/`,
  cart: `${base_site}cart/`,
  ghest_details: `${base_site}ghestiDetails/`,
  sale: `${base_site}siteSale2/`,
  call_request_marketing: `${base_site}call_request_marketing`,
  motive_quote: `${base_site}motivational_quote`,
  week_plan: `${base_site}week_plan`,
  grades_and_majors: `${base_site}grades_and_majors`,
  wants_ghesti: `${base_site}`,
  password: `${base_site}password/`,
  buy_cart: `${base_site}buyCart/`,
  specialKelasesList: `${base_site}specialKelasesList/`,
  singleKelas: `${base_site}singleKelas/`,
  singleDore: `${base_site}singleDore/`,
  singleTeacher: `${base_site}singleTeacher/`,
  check_login_land: `${base_site}SpecialDates
`,
};
export default urls;
